# Generated by Django 3.1.4 on 2021-02-28 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0003_about_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='aboout',
            new_name='about',
        ),
    ]
