# Generated by Django 3.1.4 on 2021-02-28 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0006_social_welcomeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='welcomeline',
            name='name',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
