# Generated by Django 3.1.4 on 2021-02-28 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0007_welcomeline_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Welcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('line1', models.CharField(max_length=50)),
                ('line2', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='WelcomeLine',
        ),
    ]
