# Generated by Django 3.1.4 on 2021-03-05 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0009_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='lang',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
