# Generated by Django 3.1.4 on 2021-03-05 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0010_project_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='repo',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
