# Generated by Django 3.1.4 on 2021-03-05 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0012_document'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='MyProject',
        ),
    ]
