# Generated by Django 3.1.4 on 2021-03-08 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0013_auto_20210306_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='social',
            name='link',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
